=== fluidos-project/REAR-data-models/models/schemas/contract.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "title": "Contract",
    "properties": {
        "ContractID": {
            "type": "string",
            "description": "The contract ID"
        },
        "Flavor": {
            "$ref": "./flavor.schema.json",
            "description": "The flavor of the contract"
        },
        "Buyer": {
            "$ref": "node-identity.schema.json",
            "description": "The buyer of the contract"
        },
        "Seller": {
            "$ref": "node-identity.schema.json",
            "description": "The seller of the contract"
        },
        "ExpirationTime": {
            "type": "string",
            "format": "date-time",
            "description": "The expiration time of the contract"
        },
        "Credentials": {
            "$ref": "credentials/liqo-credentials.schema.json"
        },
        "NetworkRequests": {
            "type": "string",
            "description": "The name of the ConfigMap containing the network request intents"
        }
    }
}

=== fluidos-project/REAR-data-models/models/examples/contract.json
{
    "ContractID": "12345-abcde",
    "Flavor": {
        "$ref": "./flavor.schema.json"
    },
    "Buyer": {
        "$ref": "node-identity.schema.json"
    },
    "Seller": {
        "$ref": "node-identity.schema.json"
    },
    "ExpirationTime": "2024-12-31T23:59:59Z",
    "Credentials": {
        "$ref": "credentials/liqo-credentials.schema.json"
    },
    "NetworkRequests": "configMap-14921"
}
