=== fluidos-project/REAR-data-models/models/schemas/intents/network-intent.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "title": "NetworkIntent",
    "description": "Schema for representing an MSPL Network Intent.",
    "properties": {
        "name": {
            "type": "string",
            "description": "The identifier of the network intent"
        },
        "source":  {
            "type": "object",
            "description": "The source of the communication",
            "properties": {
                "isHostCluster": {
                    "type": "boolean",
                    "description": "The source is in the host cluster"
                },
                "resourceSelector": {
                    "description": "Selector for the source",
                    "oneOf": [
                        {
                            "type": "object",
                            "title": "podNamespaceSelector",
                            "properties": {
                                "pod": {
                                    "type": "array",
                                    "description": "one or many key-value pairs.",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "key": { "type": "string" },
                                            "value": { "type": "string" }
                                        }
                                    },
                                    "minItems": 1
                                },
                                "namespace": {
                                    "type": "array",
                                    "description": "one or many key-value pairs.",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "key": { "type": "string" },
                                            "value": { "type": "string" }
                                        }
                                    },
                                    "minItems": 1
                                }
                            }
                        },
                        {
                            "title": "cidrSelector",
                            "type": "string",
                            "description": "CIDR range selector for the destination"
                        }
                    ]
                }
            }
        },
        "destination":  {
            "type": "object",
            "description": "The destination of the communication",
            "properties": {
                "isHostCluster": {
                    "type": "boolean",
                    "description": "The destination is in the host cluster"
                },
                "resourceSelector": {
                    "description": "Selector for the destination",
                    "oneOf": [
                        {
                            "type": "object",
                            "title": "podNamespaceSelector",
                            "properties": {
                                "pod": {
                                    "type": "array",
                                    "description": "one or many key-value pairs.",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "key": { "type": "string" },
                                            "value": { "type": "string" }
                                        }
                                    },
                                    "minItems": 1
                                },
                                "namespace": {
                                    "type": "array",
                                    "description": "one or many key-value pairs.",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "key": { "type": "string" },
                                            "value": { "type": "string" }
                                        }
                                    },
                                    "minItems": 1
                                }
                            }
                        },
                        {
                            "title": "cidrSelector",
                            "type": "string",
                            "description": "CIDR range selector for the destination"
                        }
                    ]
                }
            }
        },
        "destinationPort": {
            "type": "string",
            "description": "The destination port of the communication"
        },
        "protocolType": {
            "type": "string",
            "description": "The protocol type of the communication"
        }
    },
    "required": [
        "name",
        "source",
        "destination",
        "destinationPort",
        "protocolType"
    ],
    "additionalProperties": false
}

=== fluidos-project/REAR-data-models/models/examples/intents/network-intent.json
{
    "name": "NetworkIntent1",
    "source": {
        "isHostCluster": true,
        "resourceSelector": {
            "pod": [
                {
                    "key": "app",
                    "value": "*"
                }
            ],
            "namespace": [
                {
                    "key": "env",
                    "value": "production"
                }
            ]
        }
    },
    "destination": {
        "isHostCluster": false,
        "resourceSelector": "10.0.0.0/16"
    },
    "destinationPort": "443",
    "protocolType": "HTTPS"
}
